version: '3'
services:
  web:
    container_name: Intent-Trainer
    build: ./Server
    labels:
        SERVICE_80_NAME: Intent-Trainer
        SERVICE_TAG: Intent-Trainer       
  rabbitconsumer:
    container_name: rabbitconsumer
    build: ./Server/RabbitMq 
    volumes: 
      - "/machine_config:/usr/src/app/machine_config"
               