version: '3'
services:
  web:
    container_name: Intent-Trainer
    build: ./Server
    ports:
      - "3000:80"
    labels:
        SERVICE_80_NAME: Intent-Trainer
        SERVICE_TAG: Intent-Trainer
    depends_on:
      - rabbitmq        
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"   